### ISSUE TITLE
Crypt Drives?

### ISSUE THREAD

**Issue by Dontmindmes** [sithis993/Crypter#28]
Can you please make it so that i can encrypt drives also? iv attempted to do so but faild

**Comment by sithis993** [comment]
Hey! yes this is possible and something that does need adding in (relatively simple too). In this case, the ransomware would encrypt all files on all attached drives (e.g. network drives, physical hard disks, attached USBs etc.), apart from C:\

Is this what you're looking for?

**Comment by Dontmindmes** [comment]
Yes encrypting any drive connected, doyou think you can add this feature please?

**Comment by sithis993** [comment]
Yes, it's something that needs adding so I'll take a look at it. I'll probably add a checkbox or something to the builder like "Encrypt Attached Drives" to make the ransomware do this. I'll add another comment and close this issue when it's done :-)
