### ISSUE TITLE
AES Key

### ISSUE THREAD

**Issue by Dontmindmes** [sithis993/Crypter#30]
https://gyazo.com/3eadecbf20bcc1552e9ae8d3ba438a40

Where do i get an AES key?

**Comment by sithis993** [comment]
This key is used to encrypt the script files of the ransomware itself for obfuscation. Not for the actual ransomware encryption. You can leave it blank, or you can create your own (just use a string of 16 characters containing numbers and letters). The default is 0123456789ABCDEF.

If you click the browse button at the top you can load the config_example.cfg file which contains an example configuration. You can also mouse over each field and you'll see a tooltip with information/help.

I think I'm going to create a PDF quite soon to try to explain some of this stuff.
