### ISSUE TITLE
Encryption of attached drives

### ISSUE THREAD

**Issue by sithis993** [sithis993/Crypter#33]
As requested by a number of users, add functionality to encrypt attached drives, such as additional internal drives, attached external drives, USBs and network shares.

There should probably also be a hierarchy here to determine which files are encrypted first:
1. Network shares
2. Attached drvies (USBs, other internals etc.)
3. C:\ directories

**Comment by Dontmindmes** [comment]
When can we see these features?

**Comment by sithis993** [comment]
Sorry, I've been quite busy over the weekend, and also with fixing a few issues that others have been experiencing. I will take a look at this tomorrow :-)

**Comment by sithis993** [comment]
Hey! I've quickly implemented this feature in an experimental state. It's committed to the _feature/attached_drive_encryption branch_, so you'll need to pull it down and checkout onto that branch. You can then use the Builder to create the executable, and it will have the new capability (encryption of all attached drives, excluding C:\). 

For the C drive, it still only encrypts that user's documents, videos, images, etc. In a real-world environment you likely wouldn't want to encrypt much more than this on C:\, or you would risk giving the user an early indication that something on their machine was awry.

Once I've done some more testing, I'll bring it into the develop branch, and eventually master. Let me know if you have any questions/problems etc.

**Comment by ozgursevgi** [comment]
vssadmin Delete Shadows ? system recovery ?

**Comment by sithis993** [comment]
Task/Issue #38 created to address the deletion of shadow copies.

As a note to self regarding this issue (33): Need to add an option to the GUI for specifying whether we should encrypt attached drives

**Comment by sithis993** [comment]
Added initial functionality for encrypting attached drives, as well as all files and folders in the user's home directory. Added GUI option in the builder for enabling or disabling this:

![image](https://user-images.githubusercontent.com/22727993/31633232-a21b9f04-b2b7-11e7-9f79-873007f0ed95.png)

See branch commits for more details

This is currently experimental and unstable. it is NOT fully tested and will certainly see changes. It will however probably do what is required until I can continue with this tomorrow. One known issue that will be addressed, is that the user will see a warning when Crypter attempts to access a DVD/floppy etc. drive

Will be added to the release once completed.

**Comment by Dontmindmes** [comment]
So only /Desktop/

will be encrypted? or desktopp/music/documents too?

**Comment by sithis993** [comment]
With this new change, every file and folder in the user's home directory will be encrypted. So that includes things like Desktop, Documents, Music etc. But also others like AppData.

This could have undesired consequences. For example, if we want to be stealthy, encrypting things AppData could cause some applications to crash if they rely on configuration files and such that are in that folder.

**Comment by sithis993** [comment]
Functionality Completed, tested and merged into Develop (#39). Will be implemented into Master and a new release will be created soon (including a distributable) once I'm happy it hasn't broken anything and have done a bit more testing.

There are four possible options here:
1. Encryption of attached drives selected
    + All attached drives (excluding C:) are encrypted
2. Encryption of User Home selected
    + Entirety of user's home directory is encrypted (Downloads, AppData, Documents, Music etc.)
3. Both selected
    + Both areas will be encrypted
4. Neither selected
    + No files are encrypted. This is useful for testing the GUI/simulating the ransomware without risking a loss of data

Will close this issue as soon as the changes are merged into Master and a new release has been created.

**Comment by sithis993** [comment]
Changes merged into Master and implemented into release 2.10, including the relevant distributable (Crypter_distributable_2.10.zip), which can be found [here](../releases). Closing issue. Please raise any bugs/problems/requests relevant to this as separate issues.
