### ISSUE TITLE
Implement deletion of file shadow copies

### ISSUE THREAD

**Issue by sithis993** [sithis993/Crypter#38]
Should have the ability to delete the shadow copies of files, and an option to use or not use this functionality in the builder

**Comment by Dontmindmes** [comment]
https://user-images.githubusercontent.com/22727993/31633232-a21b9f04-b2b7-11e7-9f79-873007f0ed95.png you posted this but i still only have this https://gyazo.com/72084266091cbe42613afa05fe659470

yes it is the latest version

**Comment by sithis993** [comment]
So these changes aren't yet on the master branch, they're only on develop. The master branch is the default branch that you'll be on when you clone the repository.

The first thing you'll need to do is pull the latest develop changes with "git pull origin develop", and then checkout onto the develop branch using "git checkout develop". You should then have these changes.

To see what branch you're on currently, you can use "git branch".

**Comment by sithis993** [comment]
This has been implemented and is being tested currently. It looks like Windows has put measures in to prevent vssadmin.exe being invoked by third party processes (Results in a "class not found" error). Consequently, had to take an approach used by locky, amongst other ransomware families:

Created a class for creating Scheduled Tasks. A Scheduled Task is created, immediately launched and then deleted. This task deletes file shadow copies and Windows allows this method

**Comment by Dontmindmes** [comment]
will this require to be ran as admin?

**Comment by sithis993** [comment]
I haven't thoroughly tested every scenario for this... primarily because It should fail silently. However, yes I think it will. If the user has admin access it should run, and if they don't then it should fail without alerting the user.

I'll try to get around to properly testing this because it's a good question. Hopefully I can look at it tomorrow.

For now I would say yes it will require admin access to properly function. Microsoft have started to take measures to try to prevent malware from being able to do things like this (deleting shadow files).

Anyway, the functionality is in the new release (version 2.30) which you can find [here](../releases). Feel free to play around with it.

Closing this issue because I have completed the original feature. Please create new issues for any bugs or requests you have regarding this and other stuff :-)
