### ISSUE TITLE
key and decryption tools

### ISSUE THREAD

**Issue by ozgursevgi** [sithis993/Crypter#40]
Hi 
local pc key (key.txt) and decryption tool local pc  :))
how to key + pc name + ip adres sending  mail, ftp, websites scripts

**Comment by sithis993** [comment]
Sorry? don't quite understand what you're asking for here I'm afraid :-)

**Comment by Dontmindmes** [comment]
I think what is is saying is how do we get the PC Name + IP address + Key and send it to email or website

**Comment by sithis993** [comment]
Ah yes. So this is essentially the Command and Control Server component. Right now Crypter doesn't have this! It's the final piece that I've yet to complete. I haven't actually addressed it as the builder piece was my main priority, but you can see that there is a task for this already (#14).

The builder is nearing completion. There are plenty of other cools things I could and will add to it, but it's in and working. Consequently, I'll be looking towards the CnC stuff soon, but it may take my some time.... web development is not really my area so I'll need to learn as I go. The plan currently is to use Flask

**Comment by sithis993** [comment]
Issue closed due to changes in project direction (see README update)
