### ISSUE TITLE
Added better error handling for misisng PyInstaller

### ISSUE THREAD

**Issue by sithis993** [sithis993/Crypter#44]
Currently, if the user doesn't have PyInstaller installed, then a CMD prompt opens during the built stating the subprocess could not find the target:

![image](https://user-images.githubusercontent.com/22727993/32318417-23bdc092-bfaf-11e7-8931-3e3c551d94d3.png)

We should have better error handling here to report this problem in the builder itself

**Comment by sithis993** [comment]
Need a dd a validation stage to check for this. Can then print the output to the console. Something along the lines of:

[<time>] Looking for PyInstaller: True

**Comment by gbm1** [comment]
please make full installing video tutorials﻿ Crypter ransomware build and execution processes v2.40

**Comment by sithis993** [comment]
Hi, yes I will look at doing this as soon as possible. The current video is pretty outdated and doesn't cover things like dependency installation, or even the builder. Not sure when this will be but I'll try to prioritise it

**Comment by sithis993** [comment]
Issue closed due to changes in project direction (see README update). Will create another issue for the video tutorial
