### ISSUE TITLE
Want to encrypt all Data on Computer

### ISSUE THREAD

**Issue by TechniChief** [sithis993/Crypter#58]
Hello
Thank you for releasing this good piece of software
I have a Feature suggestion, to disable Crypter GUI closing and after the decryption finished, it exits.
Thanks

**Comment by TechniChief** [comment]
Disable Task Manager doesn't work also

**Comment by TechniChief** [comment]
Thank you for the info. Please keep working on this great piece it has a potential.

**Comment by apppack** [comment]
Hi,

If you want to encrypt other drives too check into Base.py "get_base_dirs" simple tweeks would do, in Crypter directory!!! Make sure you exclude the folders like Program Files, Windows etc...

Hope that helps.

**Comment by TechniChief** [comment]
Thank you very much for the Information.
