### ISSUE TITLE
Main Returned -1

### ISSUE THREAD

**Issue by apppack** [sithis993/Crypter#59]
Hi,
Thanks for developing the software...
I hope you have a time to have look at this I am using your 2.41 version everything goes fine, it creates around 9 MB Crypter.exe (With UPX Packer around 6.5) but when I run the exe it throws fatal error "Main returned - 1"... The Notebook I am trying to run exe is in German language.
I also forgot to mention that initially builder.py was throwing an error "OrderDict" not found but when I changed the import in Base.py to "from collections import orderdict" builder.py worked.
Waiting for your response.

Regards,

**Comment by apppack** [comment]
Yes you were completely right, may be was too tired :D, this morning removed python completely and was able to run it as expected, great work by the way... 

On a note I was able to test it with further customization (I am not python pro..:).) but i was able to encrypt the files even in other folders and drives and exclude the Program files as well as windows....

Great work once agian...

**Comment by sithis993** [comment]
Aha nice! as you probably know, pretty much anything you can't customise via the builder can be adjusted in base.py :-) thanks, have fun ;-D
