### ISSUE TITLE
PLEASE KEEP DEVELOPING THANK YOU VERY MUCH

### ISSUE THREAD

**Issue by 73CH9ICH13F** [sithis993/Crypter#63]
Hey Sithis
As the title says please keep Developing.
Keep going
Thank You

**Comment by sithis993** [comment]
My apologies, I've been very busy with a few other projects recently but I hope to do some development work very soon. I didn't really have any way of messaging you, but I wanted to say thank you very much for your donation. It is greatly appreciated :-)

**Comment by 73CH9ICH13F** [comment]
No problem Fam. There will be more Donation :)
Do you have Discord where we can keep in contact ?

**Comment by sithis993** [comment]
Yeah my ID is 4099 :-)

**Comment by sithis993** [comment]
username is "altire" btw

**Comment by 73CH9ICH13F** [comment]
Thanks

**Comment by 73CH9ICH13F** [comment]
It didn't worked

**Comment by 73CH9ICH13F** [comment]
![discord](https://user-images.githubusercontent.com/30529878/49222199-820bd100-f3db-11e8-94fe-9503301ddc51.PNG)
Is it you ?

**Comment by sithis993** [comment]
Yes haha that is me xD

**Comment by 73CH9ICH13F** [comment]
Alright m8.

**Comment by byehack** [comment]
> ![discord](https://user-images.githubusercontent.com/30529878/49222199-820bd100-f3db-11e8-94fe-9503301ddc51.PNG)
> Is it you ?

😐😐

**Comment by sithis993** [comment]
New release is coming soon
