### ISSUE TITLE
Error while installing pypiwin32-219.win32-py2.7.exe

### ISSUE THREAD

**Issue by 73CH9ICH13F** [sithis993/Crypter#64]
Hello Again
I'm getting suddently Issue while I'm installing pypiwin32-219.win32-py2.7.exe
Thanks
![python error](https://user-images.githubusercontent.com/30529878/49169615-6c929a80-f33a-11e8-8a10-13a545af7311.PNG)

**Comment by 73CH9ICH13F** [comment]
The Error came when I was installing the dependencies. The File pypiwin32-219.win32-py2.7.exe

**Comment by sithis993** [comment]
Hmmm I haven't quite got time at the moment to test this, but have you seen the following:
https://stackoverflow.com/questions/11106281/error-installing-and-running-pywin32-2-7

There are two things I want to do with this project as the main priorities, and both of these go hand-in-hand with each other:
- Upgrade Crypter to Python 3.x
- Resolve the dependency issues by creating a PyPi package for Crypter

The creation of a pypi package will will make life easier for everyone, as the dependencies will be auto-installed :-)

**Comment by 73CH9ICH13F** [comment]
Worked out now opened a CMD Windows and started from there out pypiwin32-219.win32-py2.7.exe
Thanks BTW
