### ISSUE TITLE
SMTP SERVER

### ISSUE THREAD

**Issue by HermesNWO** [sithis993/Crypter#68]
Hello, 
I try to add some components to your code and I'm building an SMTP server to send the KEY & ID to an email! 
But inside the Crypt.py my code don't want to sit, contact me in private if you want to know more ! 

Thanks !

**Comment by Mrcosta20** [comment]
hola me podrias decir si al fin pudistes implementar el servidor SMTP de este crypter

**Comment by Mrcosta20** [comment]
> Hola,
> trato de agregar algunos componentes a su código y estoy creando un servidor SMTP para enviar la CLAVE y la ID a un correo electrónico.
> Pero dentro de Crypt.py mi código no quiere sentarse, contáctame en privado si quieres saber más.
> 
> Gracias !

hello at last you could make the key is sent by SMTP and how did you implement it thanks
