### ISSUE TITLE
builder not opening

### ISSUE THREAD

**Issue by sh1va73** [sithis993/Crypter#78]
I cloned the repository on Win10, installed the requirements and then run builder.pyw. But nothing happens, the builder does not open. How can I fix?

**Comment by sithis993** [comment]
Hey, sorry you're having a problem. Can you open a command prompt and run Builder.pyw with "python Builder.pyw". If there are any exceptions or errors, we should see them in the terminal.

Note: If you're running Crypter in a virtual environment with _virtualenv_, you'll need to make sure your terminal is running from that virtual environment

**Comment by sh1va73** [comment]
Thanks for getting back at me this fast. I did try it in a terminal but nothing shows up. No errors or exceptions.

**Comment by sithis993** [comment]
Hmmm that's odd. Sorry the delay in replying. Can you please rename Builder.pyw to Builder.py, then run "python Builder.py" in a terminal, screenshot the output and post it here? thanks

**Comment by sithis993** [comment]
Any update on this? If you don't reply in a few days I'll assume you resolved the problem and will close the issue :-)

**Comment by sh1va73** [comment]
Thanks for getting back. Now I get an error that python3.8 is not supported. I will try with python3.6 later on.

**Comment by sithis993** [comment]
Oh that's actually good! sounds like you're nearly there. Crypter requires Python 3.7 because one of the components we use (PyInstaller) doesn't yet support Python 3.8. If you install Python 3.7, I think things should work as expected

**Comment by mamria33** [comment]
Dear Sithis, I have the following error while trying to run in CMD
Traceback (most recent call last):
  File "builder.py", line 7, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

**Comment by mamria33** [comment]
Dear Sithis,   have the following :
Traceback (most recent call last):
  File "Builder.pyw", line 34, in <module>
    builder = Builder()
  File "C:\Users\mamri\AppData\Local\Programs\Python\Python37\Crypter-master\CrypterBuilder\Builder.py", line 27, in __init__
    self.__builder_gui = Gui()
  File "C:\Users\mamri\AppData\Local\Programs\Python\Python37\Crypter-master\CrypterBuilder\Gui.py", line 40, in __init__
    MainFrame.__init__( self, parent=None )
  File "C:\Users\mamri\AppData\Local\Programs\Python\Python37\Crypter-master\CrypterBuilder\BuilderGuiAbsBase.py", line 557, in __init__
    sbSizer11.Add( bSizer4122, 1, wx.ALIGN_CENTER_VERTICAL|wx.EXPAND, 5 )
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at ..\..\src\common\sizer.cpp(2077) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored in vertical sizers

**Comment by sithis993** [comment]
Hey Mamria, sorry for the delay in responding. Can you confirm the version of wxPython you're using? I've fixed the problem you're having but if you're using the wrong version of wxPython then it may resurface with a different component of the Builder. 

Can you do a git pull so you're using the latest version of Crypter ([3.5](https://github.com/sithis993/Crypter/releases/tag/3.5)) and try this again?

**Comment by sithis993** [comment]
Any update on this? :-)

**Comment by sithis993** [comment]
Closing this issue as it's been a while. Feel free to open another issue if you're still having problems
