### ISSUE TITLE
cannot find wx module

### ISSUE THREAD

**Issue by amitrajputfff** [sithis993/Crypter#80]
please help me anyone who succesfully usses this 
i cant install requirements first but then anyway i installed them but then too i cant use this

**Comment by sithis993** [comment]
Hey there, sorry you're having problems. I don't quite understand what you mean here. Why couldn't you install the requirements? what problems are you having?

**Comment by amitrajputfff** [comment]
Actually pip install requirements.txt doesn't works as it shows no module named or no version showed so i tried installing all the modules with pip3 and it worked then when i just tried building builder.pyw it shows the message no module named wx

**Comment by sithis993** [comment]
Hmmm.. what version of Python are you using?

**Comment by amitrajputfff** [comment]
Ussing Kali Linux I have All Versions 1/2/3.7

**Comment by pretech86** [comment]
me too have this problem , any update ?

**Comment by sithis993** [comment]
Sorry, maybe it should be made clearer but this project only supports Windows right now, which is why it won't be working for you
