### ISSUE TITLE
problem with pip install -r requirements.txt

### ISSUE THREAD

**Issue by zeroANDtwo** [sithis993/Crypter#82]
when installing dependencies it raises the following error can anyone advise thanks dik 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

C:\Users\pc\Desktop\Crypter-3.4>pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
**ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'**

C:\Users\pc\Desktop\Crypter-3.4>

**Comment by sithis993** [comment]
Wow, I'm amazed I've made this mistake and no one has raised it, I'm such an idiot. My bad, I'll take a look at this ASAP and correct the filename

**Comment by sithis993** [comment]
I've fixed this now with a hotfix in the latest release (3.4a)
