### ISSUE TITLE
Hey, May I know how long does it take to run the build and display the GUI?

### ISSUE THREAD

**Issue by rashafathima** [sithis993/Crypter#84]

**Comment by sithis993** [comment]
Hey :-) are you having problems or just wondering? It probably takes about 30 seconds to a minute for the build to run. Then when you run the exe, it can take a while for the GUI to appear because it's encrypting files in the background, so depends on how many files are being encrypted

**Comment by rashafathima** [comment]
Thank you :) Actually it's been around 60+ minutes and the GUI has not appeared yet. :(

**Comment by sithis993** [comment]
No probs. Hmmm, perhaps what you're doing isn't quite right. Does it look like the build has finished? is the progress bar full? The ransomware doesn't actually run straight away after it's been built, you'll need to open the exe yourself. If you click the "Open Containing Folder" button once the build has finished, it should take you to where the binary is located.

**Comment by rashafathima** [comment]
![{6E970AD4-CE7F-4784-93B0-025241C6CD7B} png](https://user-images.githubusercontent.com/66318514/97718106-896a1680-1aeb-11eb-9f94-c6b04ae6a363.jpg)
Actually, its a taking a quite long time for the build to run. Yeah and i did open the exe itself :(

**Comment by sithis993** [comment]
Ahhhh I see... I think something might have broken in the background. Can you run Builder.pyw from a command prompt/terminal session and try again? When it gets to that same point, have a look in the command prompt and see if there are any errors... I reckon there will be something

**Comment by rashafathima** [comment]
I've tried doing that but all it gives is a blank!

**Comment by rashafathima** [comment]
![{9BF65910-FE79-4C0B-8FF7-D0A66538D799} png](https://user-images.githubusercontent.com/66318514/97774084-f4aef980-1b7a-11eb-924d-789637201c61.jpg)
Hey, i have actually tried redoing the whole process in a different acc and this time i downloaded the code form develop branch. After i run the exe. I get this error message:( How can i fix it? My current py version is 3.9

**Comment by rashafathima** [comment]
Thanks ! My problem is solved!

**Comment by sithis993** [comment]
Sorry for the delay. Glad you got things sorted! What was the problem?

**Comment by rashafathima** [comment]
Hey! Actually I tried redoing the whole process in another acc and it worked!
