### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by crocogab** [sithis993/Crypter#85]
hello yesterday I tested your program in order to understand it.
Nothing happened while the encryptor was running, so I deleted it with the key. But this morning when I restarted my pc my files were encrypted :) so I no longer have the key. Can I find my files without keys? Otherwise it doesn't matter, I just had to be more vigilant.
Thank you for your reply

**Comment by barneynoble** [comment]
to the best of my knowledge - if you haven't set the key yourself then it'll autogenerate one. if you've deleted the autogenerated key i'm afraid there's not much anyone can do for you.

**Comment by crocogab** [comment]
Ok Thx
